name: deno-format

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: check code format
        run: deno fmt --check

