name: deno-dependency

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 5"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Config properties file
        run: |
          cp .env.defaults .env
          rm deno.lock
      - name: Update dependencies
        run: |
          deno run -A https://deno.land/x/udd/main.ts src/import_map.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          commit-message: "chore(deps): update deno.lock"
          title: "chore(deps): update deno.lock"
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).
          branch: dependencies/deno-dependency-updates
          delete-branch: true
          token: ${{ steps.app-token.outputs.token }}
