name: deno-dependency

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 5"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
      - name: Config properties file
        run: |
          cp .env.defaults .env
      - name: Check dependency updates
        run: |
          deno update --compatible --frozen=false
      - name: Install dependencies and lock file
        run: |
          deno install --reload --frozen=false --allow-scripts
      - name: Check for compilation errors
        run: |
          deno task check
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          commit-message: "chore(deps): update dependencies and lock file"
          title: "chore(deps): update dependencies and lock file"
          body: >
            This PR updates the dependencies in `deno.lock` and `import_map.json`.
            It is automatically generated by the Deno dependency update workflow.
          base: dev
          branch: dependencies/deno-dependency-updates
          delete-branch: true
          token: ${{ steps.app-token.outputs.token }}