name: Quality

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 5"

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v7
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: 2.9.3
      - name: Config properties file
        run: bash .github/scripts/config-env.sh
      - name: Cache dependencies
        run: deno cache --import-map src/import_map.json src/mod.ts
      - name: Check dependency updates
        run: |
          deno update --latest --frozen=false
      - name: Install dependencies and lock file
        run: |
          deno install --reload --frozen=false --allow-scripts
      - name: Check for compilation errors
        run: |
          deno task check
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        id: pr
        with:
          commit-message: "chore(deps): update dependencies and lock file"
          title: "chore(deps): update dependencies and lock file"
          body: >
            This PR updates the dependencies in `deno.lock` and `import_map.json`.
            It is automatically generated by the Deno dependency update workflow.
          base: dev
          branch: dependencies/deno-dependency-updates
          delete-branch: true
          token: ${{ steps.app-token.outputs.token }}
