name: Release Drafter

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-config.yml
          commitish: main
          publish: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
